=pod

=head1 NAME

Dresden::TestHelper - Utility functions used in Tests.

=head1 extends L<Exporter|Exporter>

Z<>

=head1 SYNOPSIS

  use Dresden;
  use Dresden::TestHelper qw(:test);
  BEGIN { $| = 1; print "1..1\n"; }
  Dresden::hello() =~ /Hello world/
   ? ok     ("hello")
   : not_ok ("hello");

See t/*.t files in this distribution.

=head1 Methods

=head2 ok ('comment);

Return ok, as needed in testing.

=head2 not_ok ('comment);

Return not_ok, as needed in testing.

=cut
